#%RAML 1.0
title: Fuel Economy
baseUri: http://www.fueleconomy.gov/ws/rest
mediaType: application/xml
uses:
  types: types.raml
traits:
  hasVclass: !include traits/hasVclass.raml
  hasYear: !include traits/hasYear.raml
  hasMake: !include traits/hasMake.raml
  hasModel: !include traits/hasModel.raml
/vehicle:
  /{id}:
    get:
      description: Return a specific vehicle record
      responses:
        200:
          body:
            application/xml:
              type: types.Vehicle
  /emissions/{id}:
    get:
      description: Return a list of emission records for specific vehicle record
      responses:
        200:
          body:
            application/xml:
              type: types.EmissionsInfoes
  /menu:
    /year:
      get:
        description: Returns a list of model years
        responses:
          200:
            body:
              application/xml:
                type: types.Menu
    /make:
      get:
        is: [ hasYear ]
        description: Return a list of makes for a particular year
        responses:
          200:
            body:
              application/xml:
                type: types.Menu
    /model:
      get:
        is: [ hasMake , hasYear ]
        description: Return a list of models for a particular year and make
        responses:
          200:
            body:
              application/xml:
                type: types.Menu
    /options:
      get:
        is: [ hasModel , hasMake , hasYear ]
        description: Return a list of model options and the associated vehicle ID for a particular year, make and model
        responses:
          200:
            body:
              application/xml:
                type: types.Menu
  /export/all:
    get:
      responses:
        200:
          body:
            application/xml:
            application/json:
/fuelprices:
  get:
    description: Return the current fuel prices
    responses:
      200:
        body:
          application/xml:
            type: types.FuelPrices
/ympg/shared:
  /ympgVehicle/{id}:
    get:
      description: Return a summary of shared user MPG data for a specific vehicle ID
      responses:
        200:
          body:
            application/xml:
              type: types.YourMpgVehicle
  /ympgDriverVehicle/{id}:
    get:
      description: Return a list of user MPG records for a specific vehicle ID
      responses:
        200:
          body:
            application/xml:
              type: types.YourMpgDriverVehicles
  /menu:
    /make:
      get:
        description: Menu of shared make
        responses:
          200:
            body:
              application/xml:
                type: types.Menu
    /model:
      get:
        is: [ hasMake ]
        description: Menu of shared models for the specified make
        responses:
          200:
            body:
              application/xml:
                type: types.Menu
  /vehicles:
    get:
      is: [ hasModel , hasMake ]
      description: List of vehicles with shared Your MPG data
      responses:
        200:
          body:
            application/xml:
              type: types.Vehicles
/recommendation/byid:
  get:
    queryParameters:
      id1:
      id2:
      id3:
    responses:
      200:
        body:
          application/xml:
          application/json:
            type: types.RecommendationSet
/smartway/vehicles:
  is: [ hasYear ]
  get:
    is: [ hasVclass ]
    queryParameters:
      state:
      callback:
    responses:
      200:
        body:
          application/xml:
          application/json:
          application/x-javascript:
/fleet/eisa141:
  get:
    is: [ hasVclass ]
    queryParameters:
      ffv:
      year1:
      year2:
    responses:
      200:
        body:
          application/xml:
          application/json:
documentation:
  - title: Headline
    content: !include docs/headline.md
